---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBddpjH2LQK4GALekUME9XqaWGG6mlZ3hAx0Mj0BX0UhmzloUxX94XXSMjPgd9LN8SN7VklkJEN/MEqP8RSA19j1wkDX5dpR4AEqdh24uNjCHYrhmgWAe8cNBYwgDwW5YV9zepcSoKBheIXlSxNspK/5CGE6oiL09gkghRUeHK+SyhiIdy2rn5su6x+0HolzMrKRSS6jvG33oEZxYb237vckWrtNTgxMgg7N4/w006E8F03mKj6wWyhHNhZMFq36PBKfdz9DIzQQVX35BExIdDdYs5kVgyGF+1/RKHdLA9qAlfvXMye1WHcH6KbwGVMu3iGEpLCqTlcmUD/d7EwxMbUSB3ndsopllvmy9xzvbkATvmqu8fBBKBC6a+a5oJ77mAdPCType386GUznfJB+9MfvbrkO3pJPvpa5ds8FB3I7rc8vnsQMrfj3yn8PtKwiKpS12+2rooEpdvKHEggRc2Cw/aACw6VmwLd17PDn0jTcNpB+sMqncYIzwAS/URZXd4BEWxo9wGtzBmoK2PiR7yFCbwIsBGPtCGKjIXt9ab481y2PgPC7ZRCL0/9XBh1/nOWegL9rNu+eq4DVrAfjdvbBSCeQ0GvcKFz3gD9BLQ3GpgrjACz5Un1XQa6ILzneeN9GBK8kuoeinw/8Q0vWu3cMPbrWUfAe5LdeCjcQgGYDl3KYyPWk2J0s2y18HqpoQ29oUsBzED2+VeGGRqIbd2TCg==
    client_secret: AgA1As3t7FURmsSruOFqZrPfvmaMblwl2fZWDV4LNcg8evcn1SqxOjWTOTxw/XzoMN43uGcOyg1EzvS5jcEz6tHTEaNOM1z8VGYw1Njttt50nJEySIhCbcNuury8b1FSp0QuuPmY4ETa9AwuU/9gDzX2/jSV+1cUEmY32gGZPRgignjsLoI8VDlY3qrWk+g+QbBEndqFWEKveTSNbF07CBIn0Sfv/AdFpajDg7j2BCScwzXKZ6VjJGGsFVB67vNqVI//OFb2nT5dJVx2CUIQnLJDNGGCLMH23OkS5ujUpBNi5P0KVRWMR3caDAXI4RmDJDhcZ0xw7wIPoozCIgFkAkDeGlDfQXoCQzzBHy0KysW4R90woC1KNgvp8VRT5UAe5QavB05eIAQp7l0wf0pLscKEbse4sK7ZzRv6QOpTnDgxrlg8ZEky8UQRk359qzjDtOkHJnSu1Dhyjp0sxeZIaz5DryTI+nNJ8WUy3hMzG+/566FsWyahXPtJUOxfKu46EyVczECJIawZr0Uv1PTbjKjvAEKPiVd/AMv+G1rvDf2PiHJx4U7DwyO9cZLsqD8uRTei38z3oklPeE/C1W4ZF4lVm/kB1JI4TKH53X+z+o/gd8qIp8pSC4HUtHny7zLOju1PeeGwOQ969Bu8Err7R/95rw+8uwu8MIfquxp7MqcM9UEBLAim8HRykTDYw74/BypwifgSwTD5vmQzf3DOJ3USP0mLu+4ozV/nTLUxWDIS1L8KRjpSdmAC6OVDR9jlqeA50unXvZAl7UUi/0hs8R8=
  template:
    metadata:
      name: tailscale-operator-oauth
      namespace: tailscale
    type: Opaque
