apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgREPLACE_WITH_KUBESEALED_CLIENT_ID
    client_secret: AgREPLACE_WITH_KUBESEALED_CLIENT_SECRET
  template:
    metadata:
      name: tailscale-operator-oauth
      namespace: tailscale
    type: Opaque
