apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgREPLACE_WITH_KUBESEAL_ENCRYPTED_WEBHOOK_URL
  template:
    metadata:
      name: alertmanager-webhook
      namespace: monitoring
    type: Opaque
