apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: telemetry-alert-routing
  namespace: telemetry-monitoring-dev
spec:
  route:
    receiver: null-receiver
    groupBy:
      - alertname
      - severity
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
  receivers:
    - name: null-receiver
