apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-user: AgREPLACE_WITH_KUBESEAL_ENCRYPTED_USER
    admin-password: AgREPLACE_WITH_KUBESEAL_ENCRYPTED_PASSWORD
  template:
    metadata:
      name: grafana-admin-auth
      namespace: monitoring
    type: Opaque
