---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-auth
  namespace: telemetry-monitoring-dev
spec:
  encryptedData:
    admin-password: AgAdoWzTbx3xQvLLrsulEAq6WMDf10QWxMN0SyaC6q1pT9/eCDcLT4AdIkvfBP2fwtma5u6DEryfXeWLLM1sO1m9f9I2Hn3MsFaDZZmiJGniXEeeUhWaMmNS57GVdtBxD3llGa2sNslCa4juYoNZcGpyoAQxD/ST/V/HSASyEGI1Cds1N0rWdZhPuuJE/YUW/hWleO30Oz2yVyEAl0P1VVcAPvXrqaa3wFCCosAwTsD0zXBxrCr4U1OecFOEGSrNWUgEAsPueCzKlyYY/DMHZdg1HUt/XX3UmYrCD0JvYAYkyfFp9WL9fUvPxWtBO+e98X7C61EunmQYipq+0chF7lmTL7LRrv2A+gBxXssMq06kRhuFjcNdksKX9LLISQV/IHJFZIhjULjuigXf5buGqEImrVrBEkCUirPZ/StVoXiP1bzGe0PhS28gSgMTU/tc/kflK7tfCtEjcngV67L8AWA4mW50ACua9VgJgBIDsK1pkxWnzGi5gf8q5F2M//UIDB5W04nLZUG+yWkpCMxjKxDe7kf5VbpFYyyAN8MOZp8DV6dytO393bB1Lzcm6//zReAZhWfM4Y48DbY8yLJgN+aTX+lyfkq4ijkdrS3AQNFh72bbJVzZWo9bFr8If9SFjwn+01SpGCwg0X3mfXBfNNOjwpnXcUSvfhA9DXlkaMqPonRHMDdx0ndmXzpw+Y+t0KDHoSk7rfOSKAZz
    admin-user: AgB63xGO9ZXsrKYqTZgFe1rJW8UMlS5RGeWu7kBxmeQPJyFIosmiwVhyburjeRKFhfzPRFht9sBXjsQI5k+n2K2eOYP1+TFGLBVC/PkkYxkvclXvefPo9lm3VO+AcNbPFgfW3KB22Bw5jehl8p02D+bLIUkH9M2inh8gKAfOl9pirakUmNlGPtcMk+nQMfrfDUo1/YRFPFvlfp6bDEgiJqeDZg+XglG5NSI8LuMu+78Pd/gQyzCFuBYdRtYJjK+iDeNMgmqz/3ESsWmFDV33/89jPzijceEQzbj33JOnhWTvPQyIZFhZW9joGDpRslWhx0XvAJtQgvTOg5BHzoUWPKtuSyA92ghdzgCbVKjXrQ356xvmUjWh/JGh0CcOs9fb0BztgUJPFFgu8PGlkoX1qLNxrHoARvD+VC3hz37JTY3VOYfNtydBSxXqq2xebI3A3ImI9+kPqj7zw04fhR/8ZZM6qa5tVlNMaQaDhZtbmvhDIYYathM5hSQaCTYL1X0snUlpuiflOYt+cHup1xg+PUemuryT7k6mwcc31+fb/nsKb2o5UFhAs+eDNg6XMkDZaeKSvnHkn1MiaO4pKuoYTIIXDo8DaQ+cUzp6sG+OiIOEWGVE30v1zl+Q2ZDjoTwkam0XD5aSPSUQ3BKIw9SNZ7EfI5kfZyneEl+tn5kjsOztgB5QFaZAgCldB5+YtDMZXzCR5nQ3mw==
  template:
    metadata:
      name: grafana-admin-auth
      namespace: telemetry-monitoring-dev
