---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCc3/fvLsFuJ33Ub60dvaePresgI/bqh5ryz8wEvwwA7SatwHUeIWcPksUNjaMf2hrkVHsUDNpp50Xx5wIzgN1kl1iPoutxFS2BsN1oK+VTOrkhbhJ2XrtDZSIeZA3ZYN2yJT3jU5jVSxM2ozxC28UlAC8FtFRKg4FAZTuOEgxa4jINo8XbBn10x750l5GNup90od9lNvJBtKOT7NSjlRaaiAIN0n9sffXY4ht630w/OGfctM+TLP1ZldFTm13cehQqYzQ3i0MoAjD/t6iw88Yi2p4XcQcmo9UEzmfbzzTRGj0wQL5acTXGVGCOu43L/mvuAgI+kB9wV3NIXlzU229pM6cc+exfirTx+PnSMf7hRKjrqSqPBuGqG2KR9zMpFy88Rts/DIGyEiKiUjyMtJQZHKsn7DvfN/Xyrnhaa3fUP3eVHoCY6DcAMCK6aGKQNsY8LC0oqiGKEN7OTFnNlWuxqtIQyG8q4x6hC8xfbdVVHBRwXUIBK9ELAVNzsaoxw2w9ooh5PsxwvYAfnnb9le5TE/38Y9xn8QlzLUEpO4qnp/Oov3dXl/nHhD13kHqd3QrwIhOswq+T+zfJ3UV6/A/RyyCvKJ0DqxZJAdFhjPB0bd9NONlKxZt+/0bbAyQ1iETRa0bARKYaIGqjwvm34wZZ5p3qRR/g/Tzo3Gh9D1qXZBDyahLQS+aV1RJh9OiUPNtAqDCVSyjwXtm5
    admin-user: AgASfebjOoz6tyXhz4uCCZqH5qKq8tMRHSP6IeOKUvtkxXGfD/iigGJGhZ5Pa9N/NOz2x5MC8WxpQU/9IDWCu4Eh7uLhgXRjHnTuD4jfoz3ohA/FenZ8wqKhBWktf5YIUrbqu2+Oe2adgPWkKdpvE4L233LcbtS2rxo68Hszcde2/aXZkiBm4VIbEiHR2k8qYQsPYKvMKVChQuFzkRd2x/UbVKUxuut/57z+Y9a481ZmVD0EQKyQrpvQC+TueLW386v4OpTLL7bFr99xs3bszSqfrKEKw8JU6N5EAr4JpwGz7HU+7qPf4n/t7TVY2m601O6ej0FAsZD/eW6F/LX6Te8Bo6jQU1EuavLT+ym4HGxdH6RX8ZC61J2XND4+Yz26uPrpq3NQ6tzC2uUZZOUn6vUIMpIjaRZwkt50NLw2ozvFu7zpE/j5dn5zJhyBdITHNY8hYYVN9QCxmk0LmMtdHRoZvG34siofCtA/u/CCMqMLhLIAJQpBCuLXfHUiej4Gb9izYgIQE6sUpiPmo9moMargvP1FvWQcOD5lExo+5RvcuYC4fCY6PEn6VniiSgP0NEVbasHiQImw8+7Pcec23+kmYa/2Y6/oDyb2aKClp8LJXko8ZBuQOmNmunoAVbIaGD+EDjRyvLMHE9nVrCvvKbkAt6qALPDV4cqZncWJtma3ljieJBNt9EwlT/WxFyjzMZNIQtCDVw==
  template:
    metadata:
      name: grafana-admin-auth
      namespace: monitoring
