apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - scrape-targets.yaml
  - prometheusrules.yaml
  - alertmanagerconfig.yaml
  - grafana-admin-sealed-secret.yaml
  - alertmanager-webhook-sealed-secret.yaml
  - prometheus-additional-scrape-sealed-secret.yaml
