apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-additional-scrape
  namespace: telemetry-monitoring-dev
spec:
  encryptedData:
    additional-scrape-configs.yaml: AgA6iU+L1CRJfSeEYtv+IODoLPAdUyr5Sur7dHn2kblPQjJrAhXKu4h9vb+RaoaX/yiOLnmtKm9b2mT7kk1f9IO1isyfEtPbz1y1ZG+SLpSvMjsXmQoNICDsSwcQKeMHg/mLHZuVN3+BYCBt9+HzillnzJnSuwQIU/ovhnKCtNsd0OMw9EqSYPOU3ewm8H/ANMLFuGJ4h4aJM2KlmSLTiYOJw2ln86q4aP0UHJwR8dH+8eho4/ftoUuPdtVSFf3oruh8MMq0pCajScOElCqivVAZz+lRy+dasgl0vb6izTmiKx9zrCfZXYywpUHZF8ZbZxTfburGSMG5lNFnOboxFOdkvmrov7XX/28TuGffnOoh1l+htlNfoW6y3uy9QUqIJZa2G4sWoGA75FtflqNA6l933Hlc6XR07zBdL96Re9ez7b9HoQWAKj+GgDG9c4GTurjtt1TY0vf6ocOK3o8iyZ/eRWo4PgD52msiAxonALc9hxef94qTDnmlT4mqk0+qqvrEf923uM+DbCh2I39WZ17Ap1NgeSGmSuqvdCOlWE7ewwYTp/nE1b9KlTTQu/WlDX9vX8R+AjCGZAmEUmaxRV9ZirebL/LDrcApUHBIWJYoHj+DlQlokbe6xVICpxfbgR+lZRdqLFDLRnrVWIjwq6LfpS37yoaIPoJHvpoKdL/uJWEtLgIgMHhFvl1VurrMqVaag5c5Rwuv5WSIdTLGcEZoHTBiDIMa2SXScRqyRnrSoXdb3/PqKF2R06diMdAdAbn0i/WbkD2G7tNf2PfzsOTWXI15Zv3RNTm1GbKESdMdqCFIp1C6FYu6zw/qVZzPYexsFBa7C1uxo7/PJPm1NMkhtIVTXhRKSRY7LrgODObLj0VEPcgUgVYHyiPa
  template:
    metadata:
      name: prometheus-additional-scrape
      namespace: telemetry-monitoring-dev
