apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-additional-scrape
  namespace: monitoring
spec:
  encryptedData:
    additional-scrape-configs.yaml: AgBNkqKLPW+H1mDYwxHJHpQQXowqUWY258tpL7NOXqqUqCBRwBk+7drRCoMXwso/o/hweBv9lvc8To1acDfIvulxd1f0HbknKprDVu9Xip04MCAgZIFgVg+RwU3kP86UoWRjekjyRtPOeTJ6FDr278hPQBm76/oB0jEFu0QYs0+oMUjfmxvdzzboHr/ATwLlJOdrkceSXnhDW0olSUB4rsUgjTsWQ62mYFKpFlIAdJuL2nAPnqx2wlbnKObAaNHzQT7oCbj9JXAyyOsElRaAcNNEPrDc5F3OsgOBjnmyrdfSpP+G/rC15Yyj7rbgCHDaVPpKyeOiQ3dAPw+7RWM1a0ncUakgPNcKJvJCUF56GMGz9UAxmwiArn14gZcGd1XjX0yRw9D0dXA8/83A5uxfkaXVW4E1TdCxRKdrZUtu3TzgkmD3HP6tgYzTr6e124qr0np52/SRI4eKAKZleMjNBDSggrNcj7sYuAZTMjXCSGfYPzYX1eUSUOezVcygxrz5MRet7vSr0xvXFA5A5WCDJ9lgEI1+WnYG5XqQiGNpR1fDYQZX8LA5b+ptQZSSJsPswLK06m1Mk/YrOugQ/NZk4/P7z9BZqzEuUZHad9kuMXc8TW5j1ybEFzbdLBdMbBf6zchLxBjiMJB9igsAnJ6T0EQlsFtgF37ke2RF5uPM8b72MM5GpKdsS5vUmyphgf6W6gf+yeu/MMXJWtAVJu/LRnwCjFdKPqcXP2XEQABKWx7PWkJf0wdisGcdzxQRAFJsALfG30TefKnHzTTS0EJSYWewZRcure1j87xAYmgFCI3LLgK6blNHrhDCnYM7+JtkltQLGC1YuAOqbTYNGrSE7R6QJCgBY3DKLxPADco1J30m0mhqpGWaqzIWTyqD
  template:
    metadata:
      name: prometheus-additional-scrape
      namespace: monitoring
    type: Opaque
