apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: telemetry-monitoring-dev
spec:
  namespaceSelector:
    matchNames:
      - telemetry-database-dev
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers
  namespace: telemetry-monitoring-dev
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/part-of: flux
  podMetricsEndpoints:
    - port: http-prom
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql-exporter
  namespace: telemetry-monitoring-dev
spec:
  namespaceSelector:
    matchNames:
      - telemetry-database-dev
  selector:
    matchLabels:
      app: postgresql
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
