apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: telemetry-database
spec:
  interval: 30m
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "16.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      remediateLastFailure: true
  values:
    architecture: standalone
    fullnameOverride: postgresql
    auth:
      username: telemetry_user
      database: telemetry
      existingSecret: postgresql-auth
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
    primary:
      persistence:
        enabled: true
        storageClass: ""
        size: 10Gi
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
