---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-auth
  namespace: telemetry-database-dev
spec:
  encryptedData:
    password: AgA+/R+cvZL2xY4wFLjtHv+0uovB/FcLzpWQlyZTCX8oGNYOphaABxy60nYh6BKViyKO1CDTxyVuWY/vM930ZvotBUEOvHJMdFEUm7gn5LCh+UgPcdeRWluwUkA2CkMoC46n+6yPwxp6UYpyFSOzbUlk8MxZL7PR/i5Iqj/MAyFSRurI7MLnri//SVOyfPdQCxih9E/5ZG3I+fpyyWsWgcoxPWWGWCX4De/aviCf0lh5UXg0Mra0BN6v+RZfBchZBPJGvY7gXS0Xxq4lqxWq/L2VbYlDsL747p1A42eiRCEifJA5R1Acfy7ezG8c9g/3KQydCnluo44mGuA86DD7RlPmd5mBbWayEk1eYHsr1abMv7zqlTuvP+lZDpl3Aom0b2YKZsN/DjotWKTOuLY9/Z6r+Z/xiWMWT7a+QFr6TJx8Pf/J2Utv4wiZBUU5noUMTm+G7gwhrazafhbhaVB5JCoZiSapki8FrryRYHRo7g+uWVHe7mXWegjJVg4+dtSA8rzNFwlKkFedGLabYiVSJyNTnMLe+wN4F24H/2gGvsg3NL8mhVYojfhdLxSPlIhIFIVdwo0lBmOTkTd0cdGF7B5iA9N/tWmr2gqr8rYI8oYt9h0alOsB8ugp9mXVAyGbpOZYjUQeXbdXZbSpQzuSHFqoC0bPKOf2M/fr2VF5CC0fG3Su9NtkdaV5JZWJjFHDcKBzUBNvtECxmbLQxDClmc4=
    postgres-password: AgDBvh/vNOV4N1xH5JZ7Gdphu8xHQpF4W+F7lIUgOMUmT0m+KZuuRd+nbUHpVXADwxNaXMFP6lHxAOTfUWam//PQo3YAmMVywcwtdk06JZFFbLVrv9K+GEVooDivtnuRxIelV9fTXojOd3P38okkKVLnragW/+AicekkTLgVNmMnoEjxZaYqmTfzC4hUUHn4N0FSRyloUw+bgYWOPwQl+Ry+sLn/nJP7hEUubBkgockdml7X+Py+3JCddO6uRDp3bsEagRyNwCBHNUBzI8okBWZ+SR9Lbp3jmvdDV5gml1O/J7wQWquSRlSHkYM7K6HY88do1UjcqD2urB5XV8pJ04F8S7QohtbLxZl1E+UBK/6/hU5RqoVdlXPHZ0eBZZw5lPqByN6dSxVhKjij/PUJVPD7efGKZlEtfxdcf7ranC13ZhLOWjQayrXCvgNd0k2S0reK35kpbbATQjNxHA8l0JqMkpEE33RI6VxQVEOxyf1y+j6AxzyGrADDN+gp7vWSNQhOzjbIVnr2K99ziu91SVnVwKZpHwdgxOGNui66Th0cqPp8im5AbFvZA5Wc1pYV9hpXNdS2kk7+AN3VLZX2AY7RtbmYMIhsiE5OeIeJD50/FcL0P+gndUwDBoN2jou773P73TChK5LmP4N8A/bj2DV0NzmM+PJElA03Bbpwn26WTbLEK69RRusiIYex48pI6NP+e+BYW24Yuv8IlyJh8qA=
  template:
    metadata:
      name: postgresql-auth
      namespace: telemetry-database-dev
    type: Opaque
