---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-auth
  namespace: telemetry-database-dev
spec:
  encryptedData:
    postgres-password: AgAIOz8zkqhsPKvlQofuqcY3EdAnvqvRZjMhx52rRFEsyLPeekXYcH7QAoTaZVDVGmF95dgPRK3o7p5tfdl2hlYU0VJgYovAoXv8FtdLvCpgtdJ4GZpUuOKPZLFpcCAscMgF98PH81GqKVatj6xNwxetoWRCyyqqD9jJofmoeHHwTaVQi2PzGtTBHsjVpohfKH094xHxQU82Zra0qG325f4AUPTPwQT5J2QMz451GlfgGrnIa6ZaGBzXwtJalN9Zr0uN9NnoZ/nCRwa7WMw/Sifh0++BOc+FiFt3RtHgD0kG7/YdxejaupZD5Vc/d9WtF904LLOM5vZ9X0BpwZNvhnWs+MqgaZbSb7+MoMhtcMAOmJ7pN9u5g27z/hBzslJ5lV5lpopOzbU42M0EwFSiUGVoFCwFp8OhXGhdnOnN3Y/6DNminW6/9J2PL72ZQqHD3ESJJppIigdNzlrz3sGAq28AwG57oh7ZpIpHQrI2Ys/CwqCTAm6qVjBD1P//r1Izg04BcKAZLhLsugg/H6CpOCeTbNt+t3hoP1w90K8J/yIZxijatj4DiBLgV7MNtfJw0E757aZ1oLepMzQ3V5/qMX+wffZv480eeYLBGCuc295lw7c2fXtKPxlAXPTrpds2HaJZIwvJInHG6SL4hSsSbQpxcSX638Uop5sX4fy/4CzLVK1G36pfQonGrZ9MsrznHVkBatj32xJ37g==
  template:
    metadata:
      name: postgresql-auth
      namespace: telemetry-database-dev
    type: Opaque
